steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=npmrc.enc
  - --plaintext-file=/root/.npmrc
  - --location=global
  - --keyring=my-keyring
  - --key=npm-key
  volumes:
  - name: 'home'
    path: /root/
#
# Build and run unit tests
#
- name: 'docker/compose:1.18.0'
  args: ['-f', 'Docker-compose-test.yml', 'run', 'sut' ]
 
# npm auth
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['config','set', '//registry.npmjs.org/:_authToken', "${_NPM_TOKEN}"]  

# npm auth scope
#- name: 'gcr.io/cloud-builders/npm'
#  args:
#  - 'config'
#  - 'set'
#  - '//registry.npmjs.org/:_authToken=${_NPM_TOKEN}'

#
# publish components
#
- name: 'gcr.io/cloud-builders/npm'
  args: ['publish']
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/