steps:
  #
  # Build and run unit tests
  #
#  - name: 'docker/compose:1.18.0'
#    args: ['-f', 'Docker-compose-test.yml', 'run', 'sut' ]

  #
  # publish components
  #
  - name: 'gcr.io/cloud-builders/npm'
    args: ['publish']