FROM node:10-slim
LABEL maintainer="developers@nchannel.com"

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN npm ci

# Bundle app source
COPY . /usr/src/app
#RUN chmod +x ./docker-scripts/*.sh

WORKDIR /usr/src/app

CMD [ "npm", "test" ]
