version: '2'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: "mock-sftp-server:test"
    environment:
      - NODE_ENV=dev
      - SOURCE_BRANCH
    volumes:
      - ./reports:/usr/src/app/reports
